[
  {
    "module" "reexporter":
    "reExports" [
      {
        "from" "reexporter.app":
        "imports" [
          {
            "as" "":
            "name" "Flask"
          }:
          {
            "as" "":
            "name" "Request"
          }:
          {
            "as" "":
            "name" "Response"
          }
        ]
      }:
      {
        "from" "reexporter.config":
        "imports" [
          {
            "as" "":
            "name" "Config"
          }
        ]
      }:
      {
        "from" "reexporter.helpers":
        "imports" [
          {
            "as" "":
            "name" "url_for"
          }:
          {
            "as" "":
            "name" "flash"
          }:
          {
            "as" "":
            "name" "send_file"
          }:
          {
            "as" "":
            "name" "send_from_directory"
          }:
          {
            "as" "":
            "name" "get_flashed_messages"
          }:
          {
            "as" "":
            "name" "get_template_attribute"
          }:
          {
            "as" "":
            "name" "make_response"
          }:
          {
            "as" "":
            "name" "safe_join"
          }:
          {
            "as" "":
            "name" "stream_with_context"
          }
        ]
      }:
      {
        "from" "reexporter.sessions":
        "imports" [
          {
            "as" "Session":
            "name" "SecureCookieSession"
          }
        ]
      }
    ]
  }:
  {
    "module" "reexporter.subpkg":
    "reExports" [
      {
        "from" "reexporter.subpkg.foo":
        "imports" [
          {
            "as" "":
            "name" "*"
          }
        ]
      }:
      {
        "from" "reexporter.subpkg.foo":
        "imports" [
          {
            "as" "":
            "name" "bar"
          }
        ]
      }:
      {
        "from" "reexporter.subpkg.foo":
        "imports" [
          {
            "as" "":
            "name" "baz"
          }:
          {
            "as" "":
            "name" "blah"
          }
        ]
      }
    ]
  }
]